name: Publish API client

on:
  workflow_dispatch:
  push:
    tags:
      - 'sdk-v*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: https://npm.pkg.github.com
          scope: '@zeyoo-app'

      - run: pnpm install --frozen-lockfile
      - run: pnpm sdk:generate
      - run: pnpm sdk:build
      - run: pnpm --filter @zeyoo-app/api-client publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
